# Setup
title: '河边的西瓜'
url: "https://geralt-zhang.github.io/"
baseurl:

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: Asia/Shanghai
analytics:
  tracking_id: UA-53167467-11

collections:
  'blob':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
